version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Use the correct Java version
    commands:
      - echo "Installing dependencies..."
      - yum install -y maven
      - mvn clean install -DskipTests  # Install project dependencies without running tests

  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test  # Execute Selenium test cases

  post_build:
    commands:
      - echo "Uploading test reports to S3..."
      - aws s3 cp target/surefire-reports/ s3://your-test-results-bucket/ --recursive
      - aws s3 cp test-output/SparkReport/ s3://your-test-results-bucket/SparkReport/ --recursive

artifacts:
  files:
    - "target/surefire-reports/**"
    - "test-output/SparkReport/**"  # Ensure the correct path for Extent Reports
  discard-paths: no
