version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - yum install -y maven
      - mvn clean install -DskipTests  # Install project dependencies without running tests

  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test || echo "Tests failed, proceeding to upload reports"

  post_build:
    commands:
      - echo "Checking if reports exist before uploading..."
      - ls -R target/surefire-reports/
      - ls -R test-output/SparkReport/

      - echo "Uploading test reports to S3..."
      - aws s3 cp target/surefire-reports/ s3://myawsbucketasbulbule1/ --recursive || echo "Surefire reports upload failed"
      - aws s3 cp test-output/SparkReport/ s3://myawsbucketasbulbule1/ --recursive || echo "Extent reports upload failed"

artifacts:
  files:
    - "target/surefire-reports/**"
    - "test-output/SparkReport/**"
  discard-paths: no
