version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Use the correct Java version
    commands:
      - echo "Installing dependencies..."
      - yum install -y maven
      - mvn clean install -DskipTests  # Install project dependencies without running tests

  build:
    commands:
      - echo "Running Selenium tests..."
      - mvn test || echo "Tests failed, but proceeding to upload reports"

  post_build:
    commands:
      - echo "Uploading test reports to S3..."
      - aws s3 cp target/surefire-reports/ s3://myawsbucketasbulbule1/ --recursive || echo "Surefire reports upload failed"
      - aws s3 cp test-output/SparkReport/ s3://myawsbucketasbulbule1/ --recursive || echo "Extent reports upload failed"

artifacts:
  files:
    - "target/surefire-reports/**"
    - "test-output/SparkReport/**"  # Ensure the correct path for Extent Reports
  discard-paths: no
